AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  appsync-ticket-api-example

  Sample SAM Template for appsync-ticket-api-example
  

Parameters:
  APIName:
    Type: String
    Description: The name for the AppSync GraphQL API to be created.
    Default: Ticket API
  MergedApiIdentifier:
    Type: String
    Description: The name for the AppSync GraphQL Merge API for the merge association.
    Default: ""
  MergeApiExecutionRoleName:
    Type: String
    Description: The ARN of the AppSync Merge API Execution Role.
    Default: ""

Conditions:
  IsMergeApiDefined: !Not [!Equals [!Ref MergedApiIdentifier, ""]]

Resources:

  SourceApiAssociation:
    Condition:
      IsMergeApiDefined
    DependsOn: 
      - AppSyncTicketSchema
    Type: AWS::AppSync::SourceApiAssociation
    Properties:
      MergedApiIdentifier: !Ref MergedApiIdentifier
      SourceApiAssociationConfig:
        MergeType: AUTO_MERGE
      SourceApiIdentifier: !GetAtt AppSyncTicketAPI.ApiId
    

  MergeApiExecutionRolePolicyAssociation:
    Condition:
      IsMergeApiDefined
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub MergeApiExecutionRolePolicyAssociationFor-${AppSyncTicketAPI.ApiId}
      Roles:
        - !Ref MergeApiExecutionRoleName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - appsync:SourceGraphQL
            Resource:
              - !Sub arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${AppSyncTicketAPI.ApiId}
              - !Sub arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${AppSyncTicketAPI.ApiId}/*


  AppSyncApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt AppSyncTicketAPI.ApiId

  AppSyncTicketAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub ${APIName}
      AuthenticationType: API_KEY

  AppSyncTicketSchema:
    Type: AWS::AppSync::GraphQLSchema
    DependsOn:
      - AppSyncTicketAPI
    Properties:
      ApiId: !GetAtt AppSyncTicketAPI.ApiId
      DefinitionS3Location: ./src/schema.graphql

  TicketTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


  TicketTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncTicketAPI.ApiId
      Name: TicketTableDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDataSourceRole.Arn
      DynamoDBConfig:
        TableName: !Ref TicketTable
        AwsRegion: !Ref AWS::Region


  AppSyncDataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: appsync.amazonaws.com
      Policies:
        - PolicyName: DataSourceDynamoPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: 
                  - !GetAtt TicketTable.Arn


  GetSingleTicketResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncTicketAPI.ApiId
      CodeS3Location: ./src/resolvers/getSingleTicket.js
      DataSourceName: !GetAtt TicketTableDataSource.Name
      FieldName: getSingleTicket
      TypeName: Query
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0


  GetAllTicketsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncTicketAPI.ApiId
      CodeS3Location: ./src/resolvers/getAllTickets.js
      DataSourceName: !GetAtt TicketTableDataSource.Name
      FieldName: getAllTickets
      TypeName: Query
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0


  CreateSingleTicketResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncTicketAPI.ApiId
      CodeS3Location: ./src/resolvers/createSingleTicket.js
      DataSourceName: !GetAtt TicketTableDataSource.Name
      FieldName: createSingleTicket
      TypeName: Mutation
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0



Outputs:
  SourceApiAssociationStatus:
    Condition:
      IsMergeApiDefined
    Value: !GetAtt SourceApiAssociation.SourceApiAssociationStatus